#ESEGUIRE LO SCRIPT SOLO QUANDO IL VIRTUAL ENVITOMENT DI PYTHON3 È ATTIVO (VENV)
#PER ATTIVARE VENV (source venv/bin/activate)
#PER DISATTIVARE VENV (deactivate)

export FLASK_APP=flasky.py
export FLASK_DEBUG=1
flask run --host 0.0.0.0

#--host 0.0.0.0 PERMETTE ALL'APPLICAZIONE DI ESSERE VISTA NELLA RETE LOCALE
